name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1

      - name: Install bats
        run: npm install -g bats

      - name: Install jq
        run: sudo apt install jq

      - name: Run tests
        run: cd "$GITHUB_WORKSPACE" && bats test/instagrab.bats
